### ISSUE TITLE
System-level notifications for workflows.

### ISSUE THREAD

**Issue by doubleforte** [github/vscode-github-actions#108]
I don't even know if this is possible with VS Code extensions, but would be great to have a system notification that a workflow has completed. That way, I can kick off a build, go do something in another app and then macOS would ping me and say "Hey! Your workflow is done!" or "Sad news, your workflow failed."

**Comment by kraenhansen** [comment]
I was just about to file this issue too. This would be a very valuable feature. This way I wouldn't have to open the run in my browser (using up screen estate), just to know when the run has completed.

Bonus points for an option to automatically "subscribe" for notifications on runs that are initiated from pushes to the current branch only.

**Comment by felipesu19** [comment]
Unfortunately this is not a feature we are ready to commit to or to put on our road map at this time. We appreciate the suggestion, and will re-open if that changes!

**Comment by kraenhansen** [comment]
I'm left wondering the same as on [my other comment](https://github.com/github/vscode-github-actions/issues/126#issuecomment-1549269133):

Is it mostly the implementation and would you be interested in merging a PR for this or is it also the eventual maintenance that you're not interested in?
