### ISSUE TITLE
Plugin stops working if workspace includes clone of GitHub wiki

### ISSUE THREAD

**Issue by areifert** [github/vscode-github-actions#111]
**Describe the bug**
When navigating to the GitHub Actions tab in VS Code, I only see the message "Unable to connect to the GitHub API, please check your internet connection" along with a Refresh button. Clicking Refresh appears to have no effect.

Tried opening the Developer Console in VS Code, and am seeing the following error message:

<img width="1840" alt="Screenshot 2023-04-06 at 10 43 05" src="https://github.com/github/vscode-github-actions/assets/5041769/ccda5936-406e-49f1-8309-f9e671ad8cb5">

My VS Code workspace has several different Git repositories in it. I tried creating a brand new workspace and added just one Git repository, and the GitHub Actions plugin works as expected. Adding more than one Git repository also seems to work fine.

After playing around with my original workspace some more, the issue appears to be stemming from a local clone of a GitHub wiki that I have included in my workspace. After removing the directory containing my GitHub wiki, the GitHub Actions plugin works as expected.

**To Reproduce**
1. Install the GitHub Actions plugin via the Extensions tab.
2. Open a workspace that has a local clone of a GitHub wiki.
3. On the GitHub Actions tab in VS Code, an error message is displayed. Clicking the Refresh button has no effect.

**Extension Version**
`v0.25.4`

**Comment by eratio08** [comment]
If the root cause of this is an expired PAT, a possible workaround here is to revoke the trusted extension grant from the Action extension. Reload and do the whole PAT setup process again. 
<img width="631" alt="image" src="https://github.com/github/vscode-github-actions/assets/5063643/dd4b2eb8-badf-485c-82dd-4f3a028a518f">

**Comment by KetchupOnMyKetchup** [comment]
The PR has been completed and the fix will be available in our upcoming release `v0.25.7`, which planned for release May 5, 2023. Thanks so much for submitting great bugs and feedback to help make the extension even better!

**Comment by KetchupOnMyKetchup** [comment]
The fix has been released and is available in `v0.25.7` 🎉 !

**Comment by areifert** [comment]
This fix appears to be working. Including a wiki repo in my workspace no longer causes the plugin to stop working. Thanks for the fix.
