### ISSUE TITLE
Use appropriate linter on `run:` scripts

### ISSUE THREAD

**Issue by brianjmurrell** [github/vscode-github-actions#114]
**Is your feature request related to a problem? Please describe.**
In a step, when I write code for a `run:` key, that code is completely unlinted by an appropriate linter, such as ShellCheck for shell scripts.

**Describe the solution you'd like**
Given that the shell used by `run:` has a known default, or can be specified with a `defaults.run.shell` in the workflow, it would be nice if the content of `run:` keys were run through the appropriate linter.

**Additional context**
The work-around here is to put all content one would otherwise write into a `run:` key into a separate file (per `step.run` -- so lots of files) and then just reference the file in the `run:`.  This leads to a lot of tab and context switching on the part of the user as one ends up with a tab open for each step one has a `run:` in.

**Comment by felipesu19** [comment]
related: https://github.com/github/vscode-github-actions/issues/65#issuecomment-1548147244

Unfortunately we don't have the ability to support this right now, and its a complex feature that would require significant thought put into it. Maybe someday.
