### ISSUE TITLE
Autocomplete

### ISSUE THREAD

**Issue by MetRonnie** [github/vscode-github-actions#117]
**Is your feature request related to a problem? Please describe.**
There does not seem to be any autocompletion/autosuggest for the keys in the YAML file.

![image](https://github.com/github/vscode-github-actions/assets/61982285/4fbf637f-9254-4213-b83a-39e72b59e263)

This is despite the fact that when you type the full key you can then hover over it see it is recognised

![image](https://github.com/github/vscode-github-actions/assets/61982285/2e24385f-15c6-4d83-8885-f1d2dabd3cb8)

**Describe the solution you'd like**
Autocomplete just like other languages. Here is an example from Python:

![image](https://github.com/github/vscode-github-actions/assets/61982285/955df054-9743-4293-98c2-28911cd7e575)

```[tasklist]
```

**Comment by elbrenn** [comment]
This extension does support completion. [IntelliSense keybindings](https://code.visualstudio.com/docs/editor/intellisense#_key-bindings) (typically crtl + space)  and `.` will both trigger completion suggestions.

<img width="454" alt="Screenshot 2023-04-14 at 12 09 38 PM" src="https://github.com/github/vscode-github-actions/assets/34719884/cd7bcc99-57f1-451f-9de5-e9e26b2eca85">


Further investigation needed for triggering suggestions as you type.

**Comment by cschleiden** [comment]
I'm closing this for now. We do support auto-completion, you might have to trigger it explicitly like suggested ☝️
