### ISSUE TITLE
Incorrect error, "Diagnostic has no source"

### ISSUE THREAD

**Issue by max-sixty** [github/vscode-github-actions#125]
**Describe the bug**

The extension seems to raise an error for a `uses` file which does exist, and then raises an internal error when selecting "Exclude" or "Rule Definition"

**To Reproduce**

This line: https://github.com/prql/prql/blob/d09c3acad05b35b3f2565c51e045b689acea10b4/.github/workflows/release.yaml#L196

**Expected behavior**

The file does seem to exist: https://github.com/prql/prql/blob/3c10f7cb6959dfcd26ca4c7c2fa21ebb3385e472/.github/workflows/build-devcontainer.yaml#L33, so I'd expect no error.

FWIW — then when clicking on either of these buttons:
<img width="420" alt="image" src="https://github.com/github/vscode-github-actions/assets/5635139/e2a27dca-8235-48c0-8d57-f38f5ac939e6">

I get a "Diagnostic has no source" error:
<img width="245" alt="image" src="https://github.com/github/vscode-github-actions/assets/5635139/586900e6-0a0a-4617-b1a2-bce26ea80497">

**Extension Version**
`v0.25.5`

**Comment by felipesu19** [comment]
Hey, can you replicate this on 0.25.7? I want to make sure its not fixed before adding to triage!

**Comment by max-sixty** [comment]
Closing as fixed!
