### ISSUE TITLE
Improve release workflow: true/false input for VS Code release to pull in Language Services + make all local NPM steps into reusable script/steps

### ISSUE THREAD

**Issue by KetchupOnMyKetchup** [github/vscode-github-actions#129]
As part of research from https://github.com/github/vscode-github-actions/issues/107 we are reducing the manual steps in our release workflow. 

Our current release workflow is documented here: https://github.com/github/workflow-development/blob/main/docs/vscode/release-new-version.md

Our current ideal scenario for release is:
1. Go to Language Services and select  "major" or "minor" or "patch" and it will pull in the previous version and increment for you based on your selection. A PR will be opened, you approve it and the release is completed.  The release and release notes will be autogenerated. 
2. Go to the VS Code repo and select  "major" or "minor" or "patch" and it will pull in the previous version and increment for you based on your selection. You will also be asked "true/false" to pull in Language Services or not. This workflow will automatically create a release PR, incrementing the VS Code and Language Services version by running the NPM steps as a script (if true was selected to pull in Language Services). 

This issue is 1 part of 4 for the release improvement. 
- https://github.com/github/vscode-github-actions/issues/132
- https://github.com/github/vscode-github-actions/issues/131
- https://github.com/github/vscode-github-actions/issues/130
- https://github.com/github/vscode-github-actions/issues/129

Tasks for this issue:

- [x] Make all local NPM steps for the VS Code Repo to update Language Services a script that updates it within the workflow as part of the same PR that is created with the updated release version for the VS Code extension. See example of PR below:
  ![Image](https://user-images.githubusercontent.com/7976517/233164642-6969448b-3b9f-49f8-b2b1-dd23bd7d1c55.png)
- [x] When kicking off a Workflow for Release, ask if "Would you like to get the latest version of Language Services" and accept true/false
- [x] Update documentation with all changes https://github.com/github/workflow-development/blob/main/docs/vscode/release-new-version.md

**Comment by felipesu19** [comment]
Ok, we were able to test this by committing a change to package-lock.json that modified language-server to an older version, the automation when run via workflow dispatch picked up the newest version. That bit is working! 

https://github.com/github/vscode-github-actions/pull/145

**Comment by felipesu19** [comment]
This pr hooks the new job to fire off of the existing release job: https://github.com/github/vscode-github-actions/pull/146
