### ISSUE TITLE
Improve release workflow: Auto-increment version for both VS Code and Language Services based on input of "major" or "minor" or "patch" release

### ISSUE THREAD

**Issue by KetchupOnMyKetchup** [github/vscode-github-actions#130]
As part of research from https://github.com/github/vscode-github-actions/issues/107 we are reducing the manual steps in our release workflow. 

Our current release workflow is documented here: https://github.com/github/workflow-development/blob/main/docs/vscode/release-new-version.md

Our current ideal scenario for release is:
1. Go to Language Services and select  "major" or "minor" or "patch" and it will pull in the previous version and increment for you based on your selection. A PR will be opened, you approve it and the release is completed.  The release and release notes will be autogenerated. 
2. Go to the VS Code repo and select  "major" or "minor" or "patch" and it will pull in the previous version and increment for you based on your selection. You will also be asked "true/false" to pull in Language Services or not. This workflow will automatically create a release PR, incrementing the VS Code and Language Services version by running the NPM steps as a script (if true was selected to pull in Language Services). 

This issue is 1 part of 4 for the release improvement.
- https://github.com/github/vscode-github-actions/issues/132
- https://github.com/github/vscode-github-actions/issues/131
- https://github.com/github/vscode-github-actions/issues/130
- https://github.com/github/vscode-github-actions/issues/129

Tasks for this issue:

- [x] Replace request for version in both Language Service and VS Code Repo with a request for "major" or "minor" or "patch" release
- [x] Based on "major" or "minor" or "patch", pull latest version and increment accordingly
- [x] Update documentation with all changes https://github.com/github/workflow-development/blob/main/docs/vscode/release-new-version.md

**Comment by KetchupOnMyKetchup** [comment]
Beth: hmm, it looks like the current [release workflow](https://github.com/actions/languageservices/blob/dd8930fd74915c44e4bfd1a3203eaf32024b0a33/.github/workflows/publish.yml#L36) uses lerna to bump multiple versions at once. I haven't worked with it (edited) 
[publish.yml](https://github.com/actions/languageservices/blob/dd8930fd74915c44e4bfd1a3203eaf32024b0a33/.github/workflows/publish.yml)

**Comment by felipesu19** [comment]
![Screenshot 2023-04-28 at 12 51 19 PM](https://github.com/github/vscode-github-actions/assets/85468376/441e73b8-dd4d-4e15-8b1b-5f0f9479d229)
