### ISSUE TITLE
Improve release workflow: Generate release notes as an automatic workflow step

### ISSUE THREAD

**Issue by KetchupOnMyKetchup** [github/vscode-github-actions#131]
As part of research from https://github.com/github/vscode-github-actions/issues/107 we are reducing the manual steps in our release workflow. 

Our current release workflow is documented here: https://github.com/github/workflow-development/blob/main/docs/vscode/release-new-version.md

Our current ideal scenario for release is:
1. Go to Language Services and select  "major" or "minor" or "patch" and it will pull in the previous version and increment for you based on your selection. A PR will be opened, you approve it and the release is completed.  The release and release notes will be autogenerated. 
2. Go to the VS Code repo and select  "major" or "minor" or "patch" and it will pull in the previous version and increment for you based on your selection. You will also be asked "true/false" to pull in Language Services or not. This workflow will automatically create a release PR, incrementing the VS Code and Language Services version by running the NPM steps as a script (if true was selected to pull in Language Services). 

This issue is 1 part of 4 for the release improvement. 
- https://github.com/github/vscode-github-actions/issues/132
- https://github.com/github/vscode-github-actions/issues/131
- https://github.com/github/vscode-github-actions/issues/130
- https://github.com/github/vscode-github-actions/issues/129

Tasks for this issue:

- [ ] Generate release notes automatically using a script or API call if possible
- [ ] Update documentation with all changes https://github.com/github/workflow-development/blob/main/docs/vscode/release-new-version.md

**Comment by felipesu19** [comment]
Do we also want to do this for the languageservice repo @KetchupOnMyKetchup ?

**Comment by KetchupOnMyKetchup** [comment]
> Do we also want to do this for the languageservice repo @KetchupOnMyKetchup ?
> 
> EDIT: I'm gonna!

I was intending this for the language services repo only actually.  

In our current release process we aren't doing the release generation for the vscode github actions repo.  It looks like it is automatically generating a generic release note: https://github.com/github/vscode-github-actions/releases
