### ISSUE TITLE
Opening a folder containing multiple repos causes the VSC to display lots of highlighted errors

### ISSUE THREAD

**Issue by scott-doyland-burrows** [github/vscode-github-actions#14]
Rather than opening a single folder that contains a repo, I have a workspace that has multiple folders and each folder is one repo, so it looks like the first screenshot below.

When I do this, the GitHub Actions extension reports lots of false positives, some shown in the second/third/fourth screenshots - all these pass fine if I open just a single folder/repo.

Can the extension be updated so it can cope with the way I am opening a workspace/folders/repos?

![image](https://user-images.githubusercontent.com/61512176/226965562-8c04b941-19df-4dba-8127-9cd7da90f051.png)

![image](https://user-images.githubusercontent.com/61512176/226965895-8731e2f8-b058-4879-891d-afbff4a7ecae.png)

![image](https://user-images.githubusercontent.com/61512176/226965982-3908d348-60dc-402d-889b-dd8c5d21a7cf.png)

![image](https://user-images.githubusercontent.com/61512176/226966068-f0618136-7dc6-466c-a1f5-a0ac492f2495.png)

**Comment by marcus13371337** [comment]
Another issue with this setup is that it seems as if the extension is unable to detect workflows
![Screenshot 2023-03-30 at 10 38 42](https://user-images.githubusercontent.com/17770075/228779963-b472a62e-473c-46ce-b9a8-8e83e1600b7d.png)

**Comment by KetchupOnMyKetchup** [comment]
A couple of the errors are also known to be issues:

The error here: 
![Image](https://github.com/github/vscode-github-actions/assets/7976517/9ee98fbf-6b95-4c93-83e0-8a0c5eac0553)
Should be resolved by: https://github.com/github/vscode-github-actions/issues/68

And the error here: 
![Image](https://github.com/github/vscode-github-actions/assets/7976517/86f64a38-46d3-49fb-a6d0-d3a6bb90ecb7)
Should be resolved by https://github.com/github/vscode-github-actions/issues/41

Once the above two issues are resolved and in `main`, we can try testing this out with multiple repos to see if they are still happening.

**Comment by scott-doyland-burrows** [comment]
What about this really odd one:

![image](https://github.com/github/vscode-github-actions/assets/61512176/04664bb8-2cc6-41a3-b886-73cf23da9a90)


![image](https://github.com/github/vscode-github-actions/assets/61512176/e1491fe2-0c18-44eb-8062-4951dc52fb65)
