### ISSUE TITLE
Cannot see workflow logs in VSC

### ISSUE THREAD

**Issue by scott-doyland-burrows** [github/vscode-github-actions#15]
I click on a workflow log, but cannot see it in VSC - as per screenshot, no log output is shown:

![image](https://user-images.githubusercontent.com/61512176/226984069-11b78945-6908-47f4-bd52-cfdd733cf577.png)

**Comment by bmiselis** [comment]
Happens to me as well.

**Comment by Araxeus** [comment]
Such an obscure error message... `cannot open` yeah but why? 😅

**Comment by altrusl** [comment]
Happens to me as well

**Comment by elbrenn** [comment]
Currently, steps within a job do not do anything when clicked. Clicking the "View logs" button on the job which the step belongs to (`terraform/terraform` in the screenshot from the issue description) will open the logs which contain all of the jobs' steps. Does this "View logs" button work as expected?

![Screenshot View logs](https://github.com/github/vscode-github-actions/assets/34719884/15c9d670-4c52-4755-9eb2-4dbb6e6ba452)

Leaving this open to add functionality at the step level 🙂

**Comment by Araxeus** [comment]
Currently, clicking the `View logs` button doesn't do anything on my pc.

**Comment by danmana** [comment]
Same for me, the button does not do anything.
There is nothing in the extension output, but in Window output I can see:
```
[error] cannot open gh-actions://my-org/my-project/%234619148297%20-%20Deploy?12539615511. Detail: Could not load logs: Error: cannot open gh-actions://my-org/my-project/%234619148297%20-%20Deploy?12539615511. Detail: Could not load logs
    at m.h (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:98:126151)

```

**Comment by scott-doyland-burrows** [comment]
> Figured out the issue. In my case the repository owner is an organization starting with an uppercase letter `Org`.
> 
> https://github.com/github/vscode-github-actions/blob/ea64b27fa051c0a0792ca02f20502942fc9d2b45/src/logs/fileProvider.ts#L13-L18
> 
> Here `owner === 'org'` is in lowercase, but in `getGitHubContextForRepo` it searches over repos where the owner is with uppercase.
> 
> https://github.com/github/vscode-github-actions/blob/ea64b27fa051c0a0792ca02f20502942fc9d2b45/src/git/repository.ts#L227
> 
> Matching by lowercase seems to fix it, I'll make a PR

My Org also has upper casse - so hoping your PR will fix it 👍

**Comment by lrotschy** [comment]
This should go out in the next release on April 14.

**Comment by danmana** [comment]
Cool, thanks for merging this. 
The latest version fixes the logs for me.

@scott-doyland-burrows does it fix it for you too?

**Comment by scott-doyland-burrows** [comment]
> Cool, thanks for merging this. The latest version fixes the logs for me.
> 
> @scott-doyland-burrows does it fix it for you too?

It doesn't seem to.  But I also tested on a lowercase owner/repo and that doesn't show the logs either, so maybe I have something else misconfigured.

**Comment by Araxeus** [comment]
Latest version fixed the logs for me
