### ISSUE TITLE
Rename VSCode npm package because of malware taking up current name

### ISSUE THREAD

**Issue by KetchupOnMyKetchup** [github/vscode-github-actions#153]
Someone created a fake npm package using our official name here: https://www.npmjs.com/package/vscode-github-actions

We get a console warning when we run `npm audit fix --force`
![Image](https://user-images.githubusercontent.com/7976517/234967707-89f7952e-a195-4d4c-9e4d-3162a34a6d8a.png)

![Image](https://user-images.githubusercontent.com/7976517/234967851-a9da0491-a7bf-4ccb-b266-3906f8587c64.png)

To do:

- [x] Rename package to @github/vscode-github-actions in `package.json`
- [x] Update package.lock.json with update-package-locks.sh
- [ ] Register an org or username on npm you own the scope associated with it so that no one but you can publish packages into that scope? Or is @github already registered?
- [ ] Make sure that the name change to @github/vscode-github-actions in `package.json` won't break anything in the VS Code marketplace
- [ ] Document what was done, why it was done, what the npm scope is, how to login to that npm scope, how to publish (if we want to in the future) in our Workflow Development repo

**Comment by KetchupOnMyKetchup** [comment]
This is how to create an organization: https://docs.npmjs.com/creating-an-organization

But if we were to use `@github` then most likely that already exists? So how would we publish to that one?

**Comment by cschleiden** [comment]
We already publish packages under the github scope. The web systems teams should be able to help.
