### ISSUE TITLE
Unable to verify the first certificate

### ISSUE THREAD

**Issue by CoolPlayLin** [github/vscode-github-actions#154]
**Describe the bug**
When I use [FastGithub](https://github.com/dotnetcore/fastgithub) to accelerate github access, there is a problem of request failure

**To Reproduce**
Use [FastGithub](https://github.com/dotnetcore/fastgithub)

**Screenshots**
![image](https://github.com/github/vscode-github-actions/assets/96709586/372ab139-82ec-4f12-82b6-5379a01a5f56)

**Extension Version**
v0.25.6

**Additional context**

```[tasklist]
- [ ] Maybe you can add an option to the 'Close Certificate Verify' to solve this problem
```

**Comment by CoolPlayLin** [comment]
@felipesu19

**Comment by felipesu19** [comment]
I think the certificate changes added in the latest release *may* fix this issue. Please try the latest version and let us know if it works.
