### ISSUE TITLE
Unable to find reusable workflow on Mac

### ISSUE THREAD

**Issue by singlewind** [github/vscode-github-actions#182]
**Describe the bug**
When reference another workflow in the same folder. The lint display error "Unable to find reusable workflow". 

**To Reproduce**
1. Create `deploy.yml` in `.github/workflows/` folder.
2. Create `ci.yml` in `.github/workflows` folder.
3. In `ci.yml` uses the `deploy.yml` as image attached.
5. See error

**Expected behavior**
No lint error. 

**Screenshots**
<img width="561" alt="Screenshot 2023-05-08 at 9 37 12 pm" src="https://github.com/github/vscode-github-actions/assets/7637/ecf4cbdf-ee7c-40fd-8950-4e460679c47c">

**Extension Version**
`v0.25.7`

**Additional context**
The workflow is working without any issue.
OS: Ventura 13.3.1 (a)
VSCode: 1.78.0 252e5463d60e63238250799aef7375787f68b4ee arm64

**Comment by muzimuzhi** [comment]
I can't reproduce the problem with the same versions for vscode and extension, but on macOS 12.6.5 (Intel).

Can you test if a system rebooting helps, as mentioned in https://github.com/github/vscode-github-actions/issues/174#issuecomment-1536175562?

**Comment by singlewind** [comment]
@muzimuzhi , restart resolves the issue. Thank you for the tips.

**Comment by LuukMoret** [comment]
Issue still occurring for me, even after reboot. Version v0.25.7 on Apple M2 13.3.1

**Comment by samitha-calcey** [comment]
What @LuukMoret has pointed out is accurate; our team is also encountering the same issue, even with the latest Extension version v0.26.1. Additionally, the Extension incorrectly indicates that the repository is not hosted on GitHub.

**Comment by sebastian-fredriksson-bernholtz** [comment]
There's another ticket for this issue that is still open here: https://github.com/github/vscode-github-actions/issues/254
