### ISSUE TITLE
Unable to connect to the GitHub API, please check your internet connection on Mac

### ISSUE THREAD

**Issue by omerls-pw** [github/vscode-github-actions#191]
**Unable to connect to the GitHub API, please check your internet connection**
I can't use the extension.

![image](https://github.com/github/vscode-github-actions/assets/112933823/4d36a709-37ba-4c58-9634-c59b98cb9112)

Error from `GitHub Actions` on `output`:

```bash
Activating GitHub Actions extension...
Error getting GitHub context
Not Found
HttpError: Not Found
	at /Users/withwhomdidyouwishtocall/.vscode/extensions/github.vscode-github-actions-0.25.7/dist/extension-node.js:2:1365761
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async /Users/withwhomdidyouwishtocall/.vscode/extensions/github.vscode-github-actions-0.25.7/dist/extension-node.js:2:1597077
	at async Promise.all (index 0)
	at async /Users/withwhomdidyouwishtocall/.vscode/extensions/github.vscode-github-actions-0.25.7/dist/extension-node.js:2:1596994
	at async /Users/withwhomdidyouwishtocall/.vscode/extensions/github.vscode-github-actions-0.25.7/dist/extension-node.js:2:1596534
	at async Ao (/Users/withwhomdidyouwishtocall/.vscode/extensions/github.vscode-github-actions-0.25.7/dist/extension-node.js:2:1596471)
	at async Rs (/Users/withwhomdidyouwishtocall/.vscode/extensions/github.vscode-github-actions-0.25.7/dist/extension-node.js:2:1621721)
	at async v.n (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:96:6644)
	at async v.m (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:96:6607)
	at async v.l (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:96:6064)
	```
OS: Mac
V.: 13.3.1
Chip: M1 Pro, 2021

**Comment by felipesu19** [comment]
Its almost impossible to debug this with just the information currently in the issue. Are you on a home network? A private network? What version of the extension are you using? 

Is it possible you tried this during one of the recent outages and weren't able to connect at that time? Do other github extensions work for you?

**Comment by omerls-pw** [comment]
I tried it on my home network again on Tue 16 @ 7:21GMT.
I'm connected with GH token

```bash
github.com
  ✓ Logged in to github.com as omerls-pw (GH_TOKEN)
  ✓ Git operations for github.com configured to use https protocol.
  ✓ Token: ghp_************************************
  ✓ Token scopes: ****, ****, ****, ****, ****, ****, ****, ****, ****, ****, ****, ****, ****, ****,  workflow, ****, ****,
```

**Comment by brandon-kyle-bailey** [comment]
Any movement on this? Am experiencing the same issue. Also connected to GH via a token

**Comment by fharper** [comment]
It needs Git enabled in Visual Studio; at least it was my issue. Check for `git.enabled` in your settings, it needs to be true.

**Comment by felipesu19** [comment]
I would suggest the usual debug steps of uninstalling the extension fully, re-installing and re-authing. I'm a little stumped on this one.

**Comment by omerls-pw** [comment]
I've did that already 🤷 
I wish I could provide more data, but that's all I've got.

**Comment by omerls-pw** [comment]
I noticed that it doesn't appear under `trusted extensions`. 
![image](https://github.com/github/vscode-github-actions/assets/112933823/82907aa2-4be3-42d6-8e0f-2e040e513c77)
I then checked all other github accounts that I had and found that it was linked to a different account. 
I signed out of the other account, removed the extension, reinstalled the extension and authorized it with the correct account. 
it's now working for the desired account.
![image](https://github.com/github/vscode-github-actions/assets/112933823/5a27bc07-cdc9-4dcc-a4bf-255b496fa001)
![image](https://github.com/github/vscode-github-actions/assets/112933823/3089e55d-cbcf-4cc5-96d5-a155ed608d53)

**Comment by jwerre** [comment]
> It needs Git enabled in Visual Studio; at least it was my issue. Check for `git.enabled` in your settings, it needs to be true.

This was the issue for me. I set `git.enabled` to `true` in my settings and restarted VS Code.

**Comment by devasheeshmallik** [comment]
Hi, I am also facing this issue and in the setting, git.enabled is already set to true. Could anyone please help me to fix this? Thanks in advance.

**Comment by scottco-slalom** [comment]
I hope cross-posting is ok.  I found tons of threads like this one, but this is what finally solved the problem for me, so I'm leaving the link in all the threads I read, as it's the only thing that worked for me: https://github.com/github/vscode-github-actions/issues/251#issuecomment-1936306267

**Comment by chanced** [comment]
I still can't get this to work, I have tried adding `"git.enabled": true"` to my config.
<img width="360" alt="Screenshot 2024-07-01 at 11 36 50 AM" src="https://github.com/github/vscode-github-actions/assets/1073892/c1c741a2-af8b-4a54-a864-49bc868f3b99">

- I am not using a proxy or a VPN 
- Github Actions is trusted (so far as I can tell):
<img width="635" alt="Screenshot 2024-07-01 at 11 35 58 AM" src="https://github.com/github/vscode-github-actions/assets/1073892/c413259b-a013-4e76-84cb-62cf20ef233c">
