### ISSUE TITLE
Configure the number of workflows in workflow list.

### ISSUE THREAD

**Issue by love8587** [github/vscode-github-actions#193]
Hi, there. 
I'm glad to this plugin was launched. Thanks for that.
I use it very often since I installed. 

I wondering if I could set the number of recent workflow list. It currently seems to be 30.
I'd like to set it less than 30 to make it simple and fast. 

<img width="287" alt="Screenshot 2023-05-13 at 8 18 19 AM" src="https://github.com/github/vscode-github-actions/assets/3261890/f29dc4fa-6be4-4a66-a51d-fc0749401bcc">

**Comment by felipesu19** [comment]
I believe the number is 30 because that's what we get from the API call. Is that number actually causing performance issues on your end? 

This sounds like an achievable feature, i'm unsure if that's a configuration that would be broadly useful however
