### ISSUE TITLE
No GitHub repositories found.

### ISSUE THREAD

**Issue by mattcaswell** [github/vscode-github-actions#197]
I have just downloaded and installed the github actions extension (v0.25.7).

I am seeing the error "No Github repositories found. Please open a folder that contains a GitHub repository"

This seems similar to #48 but my repository is locally checked out and contains a ".github" directory with CI workflows. I have opened the folder via "File...Open Folder..." but the error persists.

I've stopped and restarted vscode as suggested in #48 with the same result.

Possibly relevant is that my local repository is configured to have many remotes pointing to various github clones of the same repository (some of which are on public github and some of which are on a private github enterprise instance).

**Comment by KetchupOnMyKetchup** [comment]
@mattcaswell - Could you please try setting your remote to a public GitHub repo and then reloading? I wonder if the first value is possibly a private github enterprise instance (currently not supported yet) and that's why it isn't working at the moment. Please try the below and let me know how it goes?

```
// List all remotes
git remote -v

// Set remote
git remote set-url <remote name> <remoteURL>
```

Reload VS Code

**Comment by mattcaswell** [comment]
> Could you please try setting your remote to a public GitHub repo and then reloading?

I assume you meant "please try setting your *first* remote".

Of course that might depend on how you define "first"! `git remote -v` seems to list remotes in alphabetical order. I amended the first alphabetical one (which was pointing at github enterprise) but it made no difference.

The first listed in my .git/config file was "origin". That was also pointing at github enterprise. Amending that to point to public github *did* solve the problem.

I also tried directly editing .git/config to put a public github remote before origin in the file. But that made no difference.

So it looks me like it always uses the remote associated with "origin". Unfortunately for me I cannot change that definition so changing it isn't workable for me.

Perhaps there needs to be some config option to specify which remote should be used?

**Comment by KetchupOnMyKetchup** [comment]
I just tested this out and this should work, but please let me know if not:

Go to Open User Settings:
![image](https://github.com/github/vscode-github-actions/assets/7976517/cbc97712-71ba-4be4-953f-d643e7810a04)

Then, extensions > GitHub Actions > Remote-name:
![image](https://github.com/github/vscode-github-actions/assets/7976517/379c6252-2670-4b37-b530-81e673f87436)

Could you please try changing this to the remote name that you want to use? Thanks!

**Comment by mattcaswell** [comment]
It works! Thank you for your support.

**Comment by Akupsmee** [comment]
logging out of all github accounts , and then logging in again fixed it for me
