### ISSUE TITLE
The input field for entering the content of secrets should accept multi-line text

### ISSUE THREAD

**Issue by nicolaerario** [github/vscode-github-actions#206]
**Is your feature request related to a problem? Please describe.**

Some `secrets` consist of text on multiple lines; for example:
- an action that needs a ssh key
- a `.env` file content 

**Describe the solution you'd like**

The input to insert secrets content should be a textarea (like on GitHub)

**Comment by cschleiden** [comment]
I agree but unfortunately this is not possible at the moment, once/if https://github.com/microsoft/vscode/issues/98098 gets fixed we could take a look.
