### ISSUE TITLE
Current Branch Workflow Status Refresh

### ISSUE THREAD

**Issue by nthewara** [github/vscode-github-actions#213]
**Is your feature request related to a problem? Please describe.**
Using Github Actions extension on VS Code to trigger workflows, however they won't appear under "Current Branch" until I manually refresh the UI.  
**Describe the solution you'd like**
Keen to understand if its possible to provide any option to automatically refresh and any new workflows to show up in the UI without needing to manually refresh. 

![image](https://github.com/github/vscode-github-actions/assets/8257850/f5282043-b30e-4667-a69d-e597df9d5f70)

**Comment by felipesu19** [comment]
This would be nice, but its not high priority. Closing, but can be reopened if someone makes a pr for it.

**Comment by mrpinkcat** [comment]
The would be a nice quality of life enhancement. It's a shame to have to refresh the section manually. A refresh at a given interval wouldn't even be necessary, given that the extension has access to the workflow files. It could poll from the push until the workflow is finished.

**Comment by danielchristianschroeter** [comment]
I’ve have developed such feature (check current branch status for a GitHub workflow continuously) by my own in a vscode extension.
Maybe it’s also helpful for you: https://marketplace.visualstudio.com/items?itemName=DanielChristianSchroeter.git-tag-release-tracker
