### ISSUE TITLE
Add "rerun failed jobs" to context menu

### ISSUE THREAD

**Issue by Ari-Kishon** [github/vscode-github-actions#214]
**Is your feature request related to a problem? Please describe.**
When right-clicking a workflow-run from the "current branch" menu, I only have the option to **``Rerun workflow run``.**
If part of my jobs failed due to flakiness i have to go to my browser to re-run just the failed jobs

![Screen Shot 2023-06-07 at 15 57 16](https://github.com/github/vscode-github-actions/assets/37385467/40e089b8-211e-4fdc-b8de-c6012c763fb1)

---

**Describe the solution you'd like**
Add another option: **``Rerun failed jobs``**, similar to whats available via the web ui.

![Screen Shot 2023-06-07 at 16 07 13](https://github.com/github/vscode-github-actions/assets/37385467/4fd93631-d5fc-4893-9f45-f45e6b525935)

---

**Additional context**
This would improve our workflow immensely as we could re-run flaky tests  without having to leave the IDE.

**Comment by felipesu19** [comment]
This would be a nice feature. Its not on our immediate roadmap. Closing, but can be reopened if someone creates a pr to do it

**Comment by hu3bi** [comment]
@felipesu19 I think that would be a really nice feature.

Without it, it forces you to always navigate to the webui.
