### ISSUE TITLE
Extension forcing tab & indent settings

### ISSUE THREAD

**Issue by CalvinWilkinson** [github/vscode-github-actions#220]
**Describe the bug**
I am setting up VSCode to have settings to enforce the indentation settings in my project by utilizing the _**settings.json**_ file.
When I have these settings set up, they work just as intended when the action is either disabled or uninstalled.

When I install or enable the extension, YAML files are forced to _**Spaces: 4**_ instead of the local VSCode settings.
I tried to find if there were any settings for the extension that controlled this behavior but could not find any.  I love and want to use the extension because it provides a tone of value and saves time, but the overriding of the YAML indentation settings is annoying.

As long as I am using the extension, I have to manually set the setting back to **_Spaces: 2_**, or my YAML layout is constantly screwed up as I develop.

**To Reproduce**
1. Create any YAML workflow file
2. Create a local **settings.json** file and set it up as shown below
```json 
{
    "[typescript]": {
	"editor.insertSpaces": false,
	"editor.tabSize": 4,
    },
    "[yaml]": {
	"editor.insertSpaces": true,
	"editor.tabSize": 2,
    },
    "[jsonc]": {
	"editor.insertSpaces": false,
	"editor.tabSize": 4,
    },
    "editor.detectIndentation": false,
}
```
4. Install and make sure that the extension is enabled
5. Place your mouse in the workflow/YAML file.  Observe the bottom right corner of the VSCode status bar to see the current setting.
![image](https://github.com/github/vscode-github-actions/assets/85414302/183df9a5-7c81-4e91-acac-c5b12c4dc89a)

**Expected behavior**
The enforcement of the indentation should be by VSCode without the extension somehow hijacking the setting.  In this context, I expect it to be set to _**Spaces: 2**_

**Screenshots**

**Extension Version**
`v0.25.7`

**VSCode Version:**
`v1.79.2`

**Additional context**
During my investigation, I disabled all the extensions.  Then I ONLY enabled the GitHub Actions extension and you can see that it goes from _**Spaces: 2**_ to being forced to **Spaces: 4**.

**Comment by cschleiden** [comment]
With the extension workflows are treated as a language separate from YAML. Try adding:

```json
"[github-actions-workflow]": {
    "editor.tabSize": 2,
    "editor.insertSpaces": true
}
```

to your config.

**Comment by CalvinWilkinson** [comment]
> With the extension workflows are treated as a language separate from YAML. Try adding:
> 
> ```json
> "[github-actions-workflow]": {
>     "editor.tabSize": 2,
>     "editor.insertSpaces": true
> }
> ```
> 
> to your config.

That worked perfectly!!  Thank you so much!!

**Comment by orfeas-k** [comment]
Would be great if this was configurable in the extensions settings by default.
