### ISSUE TITLE
Various Extension Errors on Enterprise Network with TLS Inspection

### ISSUE THREAD

**Issue by blakemotl-RL** [github/vscode-github-actions#225]
**Describe the bug**
The extension throws various errors about not being able to connect to web resources because of a certificate error. For example:
`Failure to retrieve username:  Ms [HttpError]: request to https://api.github.com/user failed, reason: unable to get local issuer certificate
    at /Users/blake.motl/.vscode/extensions/github.vscode-github-actions-0.25.8/dist/server-node.js:2:2786469
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /Users/blake.motl/.vscode/extensions/github.vscode-github-actions-0.25.8/dist/server-node.js:2:2858428
    at async va.get (/Users/blake.motl/.vscode/extensions/github.vscode-github-actions-0.25.8/dist/server-node.js:2:2868607)
    at async /Users/blake.motl/.vscode/extensions/github.vscode-github-actions-0.25.8/dist/server-node.js:2:2858363
    at async la (/Users/blake.motl/.vscode/extensions/github.vscode-github-actions-0.25.8/dist/server-node.js:2:2858330)
    at async /Users/blake.motl/.vscode/extensions/github.vscode-github-actions-0.25.8/dist/server-node.js:2:2862166
    at async Object.getContext (/Users/blake.motl/.vscode/extensions/github.vscode-github-actions-0.25.8/dist/server-node.js:2:2862122)
    at async oi (/Users/blake.motl/.vscode/extensions/github.vscode-github-actions-0.25.8/dist/server-node.js:2:2735342)
    at async gn (/Users/blake.motl/.vscode/extensions/github.vscode-github-actions-0.25.8/dist/server-node.js:2:2760637) {
  status: 500,
  request: {
    method: 'GET',
    url: 'https://api.github.com/user',
    headers: {
      accept: 'application/vnd.github.v3+json',
      'user-agent': 'VS Code GitHub Actions (0.25.8) octokit-rest.js/19.0.7 octokit-core.js/4.1.0 Node.js/16.17.1 (darwin; arm64)',
      authorization: 'token [REDACTED]'
    },
    request: { hook: [Function: bound bound e] }
  }
}
[Error - 12:14:59 PM] Unhandled error while validating: request to https://api.github.com/user failed, reason: unable to get local issuer certificate`

Notably the intermediate certificate issued by the TLS inspection service is trusted in the MacOS keychain and is set via NODE_EXTRA_CA_CERTS. I have also tried several extensions that claim to expose the system trust store to VSCode extensions, but none of them have worked.

**To Reproduce**
I have been able to reproduce this issue on several coworkers computers.
1. Use any TLS inspection agent, Netskope, ZScaler, Cloudflare ZT, etc.
2. Install the extension and open a workflow file.
3. The extension will start throwing errors, especially if you click on a reference to a reusable action.

**Expected behavior**

**Screenshots**
<img width="459" alt="image" src="https://github.com/github/vscode-github-actions/assets/69175518/7ede62f6-0c1b-40c3-b25c-d760504e3c4c">

**Extension Version**
v0.25.8

**Additional context**

**Comment by hearncode** [comment]
it ifseeand flow wolckrow ruoy rof ecruos edocGitHub buhtig gnisu yrT

**Comment by wattachai-lseg** [comment]
I'm getting exactly the same error on vscode 1.80.1 with the extension v0.25.8

**Comment by blakemotl-RL** [comment]
Closing as this is a duplicate of #39
