### ISSUE TITLE
"Suupported" typo when hovering over `types`

### ISSUE THREAD

**Issue by MicaelJarniac** [github/vscode-github-actions#227]
**Describe the bug**
> The types of workflow run activity that trigger the workflow. Suupported activity types: `completed`, `requested`, `in_progress`.

The grammar seems off too.

**To Reproduce**
1. Open an action
2. Hover over `on: workflows: types:`
3. Read

**Expected behavior**
> The types of workflow run activity that trigger the workflow. Supported activity types: `completed`, `requested`, `in_progress`.

**Screenshots**
![image](https://github.com/github/vscode-github-actions/assets/19514231/f072fe02-d0d1-4fba-97da-94a5de078c2a)

**Extension Version**
`v0.25.8`

**Additional context**
I tried searching for this typo in the codebase, issues, and PRs, and couldn't find it.

**Comment by muzimuzhi** [comment]
The source file is part of another repo and I've filed a PR for current issue, see https://github.com/actions/languageservices/pull/47.

**Comment by KetchupOnMyKetchup** [comment]
Note: this won't go until until we do the next release to `v0.25.9`, we are currently on `v0.25.8`. Thanks so much @muzimuzhi for fixing this and putting in a PR for it and thank you @MicaelJarniac for reporting this ❤️ !
