### ISSUE TITLE
if always() should throw a linter warning recommending not to use it

### ISSUE THREAD

**Issue by sammcj** [github/vscode-github-actions#228]
**Describe the bug**

The linting provided by the vscode extension for Actions should throw a warning when using if always().

if always() is unreliable (by Github) and may cause Github Actions runs to be stuck in a state where no one but Github support can cancel them. This can lead to situations where customers end up being blocked from deploying/building etc...

https://github.com/orgs/community/discussions/25789

**To Reproduce**

N/A

**Expected behaviour**

A warning in the linter when if always() is used.

**Screenshots**

![image](https://github.com/github/vscode-github-actions/assets/862951/ca46b1e7-80de-4802-9e39-44f0b9fe674d)

**Extension Version**

v0.25.8

**Additional context**

Github Support suggested I log this here.

![image](https://github.com/github/vscode-github-actions/assets/862951/461b6c08-444c-4a99-90c3-3439e3fa2d42)

**Comment by elbrenn** [comment]
@sammcj I see that `if always()` did not work for your scenario, however this is valid syntax and showing a warning would create noise for customers using this feature intentionally. 

The [always function](https://docs.github.com/en/actions/learn-github-actions/expressions#always) is intended to ensure a job runs in all conditions. The discussion you linked is a great place for feedback on the `always` function as a whole. We won't be discouraging its use in the extension.
