### ISSUE TITLE
Notification Popup in VSC after workflow run is complete

### ISSUE THREAD

**Issue by felixele217** [github/vscode-github-actions#237]
When a workflow run is finished, it would be nice to get a popup notification inside VSCode. Therefore I would immediately be informed about the result of my CI/CD flow. Sometimes I tend to oversee a failed pipeline because I do not always take the extra effort to check the result in the browser.

Would be super cool! 🙏

**Comment by felipesu19** [comment]
We've discussed this but unfortunately the lift isn't worth the effort for this feature right now.
