### ISSUE TITLE
List available inputs for `with:` statements for `uses:` steps

### ISSUE THREAD

**Issue by jsoref** [github/vscode-github-actions#288]
**Is your feature request related to a problem? Please describe.**
When entering values into a `with:` for a `uses:`, the extension will tell you if an input isn't recognized:
<img width="814" alt="image" src="https://github.com/github/vscode-github-actions/assets/2119212/1a54641c-3289-4c69-93dd-d6478f32f579">

In order to do that, it _must_ know which inputs _are_ recognized.

**Describe the solution you'd like**
 It'd be really handy if the box had a row for `Available inputs` and it'd be even better if there was completion for those inputs.

**Additional context**
The extension is parsing the uses line and makes a link to the directory containing its `action.yml` (e.g. [`check-spelling/check-spelling@prerelease`](https://github.com/check-spelling/check-spelling/tree/prerelease/)):
<img width="336" alt="image" src="https://github.com/github/vscode-github-actions/assets/2119212/d1a23b9f-6ca9-415b-8ca3-e242420ef93e">

**Comment by cschleiden** [comment]
This is supported by the extension, is that not working for you? Example: 

![Image](https://github.com/github/vscode-github-actions/assets/2201819/d3cf6273-cb6c-4311-bed8-519e268f1ef6)

Closing this for now, if it doesn't work for you please open a bug issue.

**Comment by jsoref** [comment]
Apparently it only triggers if i use control-space, otherwise, there's no hint of anything:

<img width="683" alt="image" src="https://github.com/github/vscode-github-actions/assets/2119212/46925e88-9de7-411f-81f0-8b3cf3f8d0a7">

Given that control-space can give a list, it seems reasonable for the error I've cited here to offer the list of valid keys or to suggest using control-space to get the list of keys.
