### ISSUE TITLE
`actions.yml` file is not getting any autocompletion

### ISSUE THREAD

**Issue by nfx** [github/vscode-github-actions#289]
**Describe the bug**
I want to experience autocompletion and click-to-definition for other github actiobs

**To Reproduce**
1. Create a folder `foo`
2. Create `foo/action.yml`
3. Start editing it as described in https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions
4. don't see any autocompletions

**Expected behavior**
Seeing autocompletions

**Screenshots**
<img width="582" alt="Pasted_Image_13_01_2024__14_05" src="https://github.com/github/vscode-github-actions/assets/259697/4afb3e32-6797-4561-92fb-e6f5e27fb817">

**Comment by andrewakim** [comment]
:wave: Hi @nfx - The extension only works for repositories _using_ actions workflows but not when building an action. I've heard this request before though and added it to the feature backlog. I'm going to close this issue out in favor of [this feature enhancement issue](https://github.com/github/vscode-github-actions/issues/46) opened last year.
