### ISSUE TITLE
Cannot "sign in to github"

### ISSUE THREAD

**Issue by ilsaloving** [github/vscode-github-actions#294]
**Describe the bug**
I just installed the extension, and when I click github actions, a side panel appears with the button "Sign in to Github".  Clicking the button does absolutely nothing.

If I open the dev console, I see the following errors appear:

```
mainThreadExtensionService.ts:113 Activating extension 'github.vscode-github-actions' failed: Timed out waiting for authentication provider to register.
$onExtensionActivationError @ mainThreadExtensionService.ts:113
log.ts:437   ERR command 'github-actions.sign-in' not found: Error: command 'github-actions.sign-in' not found
    at k.n (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1568:12343)
    at k.executeCommand (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1568:12272)
    at async c.open (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:657:44311)
    at async h.open (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:657:45692)
```

**To Reproduce**
1. Install the extension
2. Click 'Github Actions' button on the left panel
3. Twiddle thumbs

**Expected behavior**
I expect it to work.

**Screenshots**

**Extension Version**
v0.26.2

**Additional context**

**Comment by clssn** [comment]
Any news or ideas for workarounds? I can't use the extension anymore - at all.
I can contribute a screenshot as evidence:
![image](https://github.com/github/vscode-github-actions/assets/6572938/53df2368-3dcf-4847-91ef-34dae366a662)

**Comment by djthornton1212** [comment]
I can corroborate. I cannot log in with the GitHub Actions extension at all either:
![image](https://github.com/github/vscode-github-actions/assets/99346713/f25a7329-bcab-40dd-a4ab-f7f74c7dafc0)

**Comment by felipesu19** [comment]
Generally speaking, we cannot help with login issues, as they are almost always networking/user specific.

**Comment by ilsaloving** [comment]
This is garbage.  It's not a login issue NOR a network issue.  If it _was_ an issue, why is there no notification or something so we can know what the problem is?  

Did you even LOOK at the error messages?  Here it is again, since reading comprehension appears to be a problem:
>mainThreadExtensionService.ts:113 Activating extension 'github.vscode-github-actions' failed: Timed out waiting for authentication provider to register.
>$onExtensionActivationError @ mainThreadExtensionService.ts:113
>log.ts:437   ERR command 'github-actions.sign-in' not found: Error: command 'github-actions.sign-in' not found

This plugin flat out doesn't work.  If you are not willing to maintain it, then hand the project over to someone who does.

**Comment by jonathan-saindon** [comment]
I had this exact problem. What fixed it for me was disabling the `Use-enterprise` setting that I had enabled to address this other issue https://github.com/github/vscode-github-actions/issues/222
