### ISSUE TITLE
Unable to connect to the GitHub API, please check your internet connection.

### ISSUE THREAD

**Issue by Nheverest** [github/vscode-github-actions#295]
**Describe the bug**
GitHub Actions extension displays: 'Unable to connect to the GitHub API, please check your internet connection.'

**To Reproduce**
Follow the 'Getting started' documentation of the extension
1. Install the extension from the Marketplace => OK
2. Sign in with your GitHub account and when prompted allow GitHub Actions access to your GitHub account => OK
3. Open a GitHub repository => OK
3. You will be able to utilize the syntax features in Workflow files => OK
4. and you can find the GitHub Actions icon on the left navigation to manage your Workflows => The icon only diplays the message 'Unable to connect to the GitHub API'

**Expected behavior**
The extension should enable workflow management, and should be able to connect to Github.

**Screenshots**
n.a.

**Extension Version**
`v0.26.2`

**Additional context**
VS Code 1.86.2, behing a proxy set in VS Code.

CoPilot extension works fine. 

Python extension works fine.

Installing, re-installing the GitHub Actions extension, signing out/in, etc. nothing helped.

Output extract:
```
Activating GitHub Actions extension...
Error getting GitHub context
fetch failed
HttpError: fetch failed
```

**Comment by impks27** [comment]
Facing the same issue. What has changed? The same plugin version used to work before. Did any of the dependent plugins change?

**Comment by lfvdaniel** [comment]
We are also seeing this issue.

**Comment by impks27** [comment]
Was anybody able to fix this? This definitely seems to be a bug.

**Comment by AaronMT** [comment]
First time user of this extension and am seeing this too. Not the best experience off the bat.

**Comment by KetchupOnMyKetchup** [comment]
Hi there, I am so sorry about this experience. We currently don't support proxies but have plans to and understand that it is important for our customers and that it is frustrating to not be able to use the extension and that Copilot does have this feature. I just added a note in the README.md so it can be publicly documented: https://github.com/github/vscode-github-actions?tab=readme-ov-file#supported-features 

@impks27 - There haven't been any recent changes. Are you using a proxy or was one added? Here are some troubleshooting steps in case you aren't using a proxy, and please reach out if these don't help. Sometimes re-installing the extension and reloading will help get it working (without a proxy):
- https://github.com/github/vscode-github-actions/issues/55#issuecomment-1503741333
- https://github.com/github/vscode-github-actions/issues/55#issuecomment-1505363848

I would like to close this issue in favor of this one (to avoid dupes and easier tracking) which has already been opened and is tracked and triaged on our project board once I get more information about the above issue with it having worked in the past but not anymore.  
https://github.com/github/vscode-github-actions/issues/189

**Comment by Nheverest** [comment]
Hello,

I am ok with closing this issue in favour of #189, though the title is a little bit misleading.
I have subscribed to #189.
I let you close this one.

Thanks!

**Comment by kizzlah** [comment]
It's happening to me now, specifically Homebrew. However, I used HB earlier to install Mactex so I'm not sure what's going on now.
