### ISSUE TITLE
I want to check the log for each job on VS Code

### ISSUE THREAD

**Issue by kai-fumiya** [github/vscode-github-actions#304]
**Is your feature request related to a problem? Please describe.**
Workflow logs can be checked on VS Code.
However, since the log for each job is a link to GitHub, I would like to be able to check the log on VS Code.

**Describe the solution you'd like**
Added the ability to output logs in VS Code for each job

**Additional context**
None

**Comment by felipesu19** [comment]
This is unfortunately not a feature we plan on shipping at this time.  If someone were to open a PR, I would review it, but outside of that this is not planned.
