### ISSUE TITLE
Choice input variable is not detected properly

### ISSUE THREAD

**Issue by sebastianbuechler** [github/vscode-github-actions#318]
**Describe the bug**
When I have input variables on a workflow everything works fine with type `string` but not with type `choice`:
![image](https://github.com/github/vscode-github-actions/assets/42775578/2d2903a5-d71f-49b3-86f5-4984fde0a1df)

I get multiple errors:
 - Missing 'options' for choice input (for all marked lines)
 - Unexpected value 'choice' (for line with `type`)
 - Unexpected value 'options' (for line with `options`)

**To Reproduce**
1. Create a new workflow file that has input variables
2. Add an input variable of type `choice`
3. See error

**Expected behavior**
No error of the linter

**Screenshots**

**Extension Version**
`v0.26.2`

**Comment by sebastianbuechler** [comment]
Edit: It seems that the `choice` type is not available for `workflow_call` at all: https://json.schemastore.org/github-workflow.json

Is there a reason for this?

**Comment by muzimuzhi** [comment]
`choice` type is only supported by [inputs of `on.workflow_dispatch` event](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onworkflow_dispatchinputsinput_idtype), not `on.workflow_call`.

> ### [on.workflow_call.inputs.<input_id>.type](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onworkflow_callinputsinput_idtype)
> Required if input is defined for the `on.workflow_call` keyword. The value of this parameter is a string specifying the data type of the input. This must be one of: `boolean`, `number`, or `string`.

**Comment by michellrachid** [comment]
Obrigado!
