### ISSUE TITLE
Add "Go to definition" feature for jobs referenced inside `needs`

### ISSUE THREAD

**Issue by EmilySeville7cfg** [github/vscode-github-actions#32]
**Is your feature request related to a problem? Please describe.**
It's not convenient not having an ability to quickly jump to some job definition which other is depending on.

**Describe the solution you'd like**
Add ability to jump to job definition in the same file by clicking on it (or via RMB menu).

**Additional context**

**Comment by felipesu19** [comment]
This is a nice-to-have which I'm not sure we can commit to right now.
