### ISSUE TITLE
Syntax highlighting is broken

### ISSUE THREAD

**Issue by NikitaChekalinskyNetra** [github/vscode-github-actions#328]
Randomly highlights errors even if there are none.

<img width="273" alt="image" src="https://github.com/github/vscode-github-actions/assets/123596355/148e2153-f873-4bbb-a741-6d17de70c577">

**Extension Version**
`v0.26.2 `

**Comment by felipesu19** [comment]
We would need significantly more information to debug. Some example broken workflows would be a good place to start. Closing pending that information, feel free to re-open with an example we can replicate with 👍
