### ISSUE TITLE
Says a working cron string is not valid

### ISSUE THREAD

**Issue by peterbe** [github/vscode-github-actions#331]
**Describe the bug**

It says that `20 */24 * * *` is not a valid cron schedule.  (see screenshot below)

**To Reproduce**
1. https://github.com/github/docs/blob/7aacc9a619dc8d01c025340ad5934fcf688a19fd/.github/workflows/sync-search-elasticsearch.yml#L20
2. Open this in VS Code
3. See warning

**Expected behavior**

That it doesn't say it's invalid.

**Screenshots**

![VS code warning](https://github.com/github/vscode-github-actions/assets/26739/baee2135-bb71-4dc1-acdf-c7396ea39cdd)

**Extension Version**
Don't know how to look that up. But I think it's the latest because it automatically upgrades itself. 

**Additional context**

I know the schedule works by looking at our Actions runs. 

I used https://crontab.guru/#20_*/24_*_*_* to see if it works there.

**Comment by muzimuzhi** [comment]
Strictly speaking, the hour field should be in range [0, 23], thus it's the `24` in `20 */24 * * *` that made the cron string invalid.
- [POSIX cron syntax](https://pubs.opengroup.org/onlinepubs/9699919799/utilities/crontab.html#tag_20_25_07)
- https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule

Testing on https://crontab.guru, [`20 */24 * * *`](https://crontab.guru/#20_*/24_*_*_*) can be replaced with valid [`20 0 * * *`](https://crontab.guru/#20_0_*_*_*).

BTW, the cron validation is done in https://github.com/actions/languageservices, file [`workflow-parser/src/model/converter/cron.ts`](https://github.com/actions/languageservices/blob/main/workflow-parser/src/model/converter/cron.ts). Looks like it's stricter than the validator used by  https://crontab.guru.

**Comment by peterbe** [comment]
You're right. It does say "Hour [0, 23]" in the spec. 
So the **strictness** is just a minor differences. Seems GitHub Actions is a bit more forgiving in this corner case. 

I changed it on our end to your recommendation and now the validator is not showing any warnings or errors.
