### ISSUE TITLE
Notifications on failed runs

### ISSUE THREAD

**Issue by mwojcik321** [github/vscode-github-actions#338]
**Is your feature request related to a problem? Please describe.**
I like the feature showing the status of workflow that run on my PR, however I don't check it very often during development. I would love to get automatic notifications inside the VS Code if the workflow fails.

**Describe the solution you'd like**
Notifications for status update of the workflows. It should be configurable to show notifications only on failed runs or only for the selected workflows.

**Additional context**

**Comment by felipesu19** [comment]
This is not a feature we have the bandwith to support at this time. If someone opened a PR I would be willing to review it.
