### ISSUE TITLE
Feature: snippets for workflow syntax and shell commands

### ISSUE THREAD

**Issue by EmilyGraceSeville7cf** [github/vscode-github-actions#36]
**Is your feature request related to a problem? Please describe.**
It's frustrating not to have any assistance while writing compound shell commands, like `for` and creating quickly steps or jobs. There is intellisence for workflow file, but it doesn't allow me to create quickly job or step definition, and also it doesn't assist me with writing shell commands at all. 

**Describe the solution you'd like**
I propose snippet creation for some workflow code pieces and shell ones. Snippets should be readable and memorizable, and reduce typing overhead. It means that they should not be necessarily short, they should be self-explanatory. At the same time, they must be almost the same as Bash IDE extension for VS Code provides, as it's convenient to reuse snippets you are already familiar with.

**Additional context**
I already created https://github.com/github/vscode-github-actions/pull/31 PR to close this issue. All workflow-related snippets doesn't contain any prefix, but snippets implementing shell commands do, for instance `bash:if`.

```[tasklist]
- [x] Workflow snippets
- [x] Shell snippets
```

**Comment by felipesu19** [comment]
We are unfortunately not ready to support snippets at this time, but it is a feature we know people would like. We'll revisit this when we have more capacity.
