### ISSUE TITLE
CI debugging feature

### ISSUE THREAD

**Issue by ohhmm** [github/vscode-github-actions#374]
**Is your feature request related to a problem? Please describe.**
Actions are ofthen matter to fail on a server

**Describe the solution you'd like**
Allow to debug it before pushing changes

**Additional context**
Consider running actions locally on development machine

**Comment by ohhmm** [comment]
Just trying to reduce GitHub hosting costs

**Comment by muzimuzhi** [comment]
Some chooses:
- [`act`](https://github.com/nektos/act) to run GitHub Actions locally
- actions like [`mxschmitt/action-tmate`](https://github.com/mxschmitt/action-tmate) for real-time GitHub Actions debugging

**Comment by felipesu19** [comment]
This is outside of the scope of this project. i agree, it'd be awesome.
