### ISSUE TITLE
Linting option to strip out all unneeded quotes for strings

### ISSUE THREAD

**Issue by garysassano** [github/vscode-github-actions#380]
**Is your feature request related to a problem? Please describe.**

I've noticed that many people include single (`'`) or double (`"`) quotes around strings in their GitHub Actions, even when they're not necessary. It would be helpful to have a linting option that automatically removes these quotes where applicable.

**Describe the solution you'd like**

An option you can set up under `settings.json` in VS Code.

**Comment by felipesu19** [comment]
unfortunately we're not supporting feature enhancements at this time. It would be nice.
