### ISSUE TITLE
`Context access might be invalid` warning shows for `push`, not for `pull_request` event

### ISSUE THREAD

**Issue by garysassano** [github/vscode-github-actions#381]
**Describe the bug**

**To Reproduce**
1. With this workflow '...'
2. Do this '...'
3. See error

**Expected behavior**
`Context access might be invalid` shows up for all kind of events where the context might be missing.

**Screenshots**
![image](https://github.com/user-attachments/assets/b97bbca8-2309-4c75-a438-e1f4b0296410)
![image](https://github.com/user-attachments/assets/15fad2f6-4d79-4b2e-8e44-deaf387e6be9)

**Extension Version**
`v0.26.3`

**Comment by garysassano** [comment]
Apparently, you access the `head_commit` property without specifying an event type (`github.event.head_commit.messag`e), even though the structure of the payload should be correct [according to the docs](https://docs.github.com/en/webhooks/webhook-events-and-payloads#push).

Also, technically the `Context access might be invalid` warning should always be displayed when accessing any event-specific context, since you have no guarantee of which event type triggered the workflow UNLESS the workflow specifies a single trigger, in which case that event type context would be guaranteed to be valid.

**Comment by garysassano** [comment]
Apparently, you access the `head_commit` property without specifying an event type (`github.event.head_commit.messag`), even though the structure of the payload should be correct [according to the docs](https://docs.github.com/en/webhooks/webhook-events-and-payloads#push).

Also, technically the `Context access might be invalid` warning should always be displayed when accessing any event-specific context, since you have no guarantee of which event type triggered the workflow UNLESS the workflow specifies a single trigger, in which case that event type context would be guaranteed to be valid.

**Comment by muzimuzhi** [comment]
Context validation is provided by https://github.com/actions/languageservices, so this seems again an issue in that repo.
