### ISSUE TITLE
GitHub Actions is down, contradicting githubstatus.com

### ISSUE THREAD

**Issue by jimmy-zhening-luo** [github/vscode-github-actions#408]
**Describe the bug**
GitHub Actions is down.

**To Reproduce**
1. Trigger a workflow run using `ubuntu-latest` (typical use-case).

**Expected behavior**
Workflow runs and completes. If not, [githubstatus.com](https://githubstatus.com) explains why not.

**Actual behavior**
Workflow hangs, uncancelable, with one of two statuses:

Job A, 1 hour ago:
![Job is waiting for a hosted runner to come online.](https://github.com/user-attachments/assets/7b46faac-be48-4ea8-8a04-a26506e26774)

Job B, 14 minutes ago:
![BLANK](https://github.com/user-attachments/assets/6ca01d62-7af6-4cf8-ab99-3458f13e72f8)

[githubstatus.com](https://githubstatus.com) tells us all is good:

![GitHub Status: All Systems Operational](https://github.com/user-attachments/assets/90f4f757-4196-4507-8c09-98053665bcc6)

However, we know this to not be the case:

![downdetector.com](https://github.com/user-attachments/assets/2da3d2c5-d34e-4eb5-923b-12929f8a2f1e)

This is not the first time this has happened this month, where GitHub Actions saw degraded performance for hours+ with no contemporaneous nor post-hoc reports on [githubstatus.com](https://githubstatus.com).

**Extension Version**
`v0.27.0`

**Additional context**

**Comment by jimmy-zhening-luo** [comment]
Got it, thank you -- I'll close out and contact

**Comment by kapicomk** [comment]
❤️❤️❤️❤️❤️❤️❤️
