### ISSUE TITLE
No github repository found. Please open a folder that contains github repository

### ISSUE THREAD

**Issue by vytautas-pranskunas-** [github/vscode-github-actions#48]
After instaling extension i see this message but I am in the folder that contains .git folder and contains github actions workflow. Any isuggestions?

**Comment by ccelebi** [comment]
Restarting vscode worked for me.

**Comment by vytautas-pranskunas-** [comment]
Tried. Sane result

**Comment by vytautas-pranskunas-** [comment]
I work with single project

**Comment by rlespinasse** [comment]
This doesn't work in `github.dev` context even  after a  restart.

<img width="431" alt="Capture d’écran 2023-03-29 à 12 41 59" src="https://user-images.githubusercontent.com/1280212/228509310-b3c1427c-45d3-4102-936a-f83d5ee21624.png">

**Comment by JacobCallahan** [comment]
@rlespinasse I encountered the same thing. This was likely designed for local repos, but github.dev support should likely be prioritized now.

![Screenshot from 2023-03-29 08-35-43](https://user-images.githubusercontent.com/6618303/228537375-7dbc9010-4140-487b-9707-5cd32d599278.png)

**Comment by daven97** [comment]
For me, this was resolved by quitting VS Code and reopening the repository in a new VS Code window after that.

**Comment by KetchupOnMyKetchup** [comment]
Hi, If you are using a [remote repository](https://code.visualstudio.com/blogs/2021/06/10/remote-repositories), github.dev, or vscode.dev (where you opened the repository without downloading the repository locally), we currently don't have full support with the GitHub Actions extension.

I believe this is the same issue as:
- https://github.com/github/vscode-github-actions/issues/78

As a workaround, if you download the repository locally, then use the GitHub Actions extension, it should work properly. 

Does anyone have this issue happening with a locally downloaded repository? If so, please let me know and leave specific repro steps or create a new issue. Thank you!

**Comment by KetchupOnMyKetchup** [comment]
I have this work tracked in the remote repository future enhancements batch (https://github.com/github/vscode-github-actions/issues/103) to ensure we don't lose track of this issue, however we currently aren't supporting remote repositories at this time.  I am going to close this for now so we can keep track of open issues that we are currently working on.

**Comment by JonnyOThan** [comment]
Please reconsider.  If you start working on a github action in github.dev, a little popup appears that asks if you want to install the recommended extension (just like in vscode).  But this ended up just wasting my time because it's not supported.

**Comment by mwisnicki** [comment]
This actually works in vscode.dev but not github.dev. Why?
