### ISSUE TITLE
Multiple accounts handling

### ISSUE THREAD

**Issue by mathwro** [github/vscode-github-actions#51]
**Is your feature request related to a problem? Please describe.**

Between internal work, private and customer accounts i'm using multiple github accounts. Currently there isn't a way to handle multiple accounts or even retrigger the login process.

**Describe the solution you'd like**

The extension being able to be logged into multiple accounts 

**Additional context**

**Comment by cschleiden** [comment]
This is something the GitHub auth provider would have to support: https://github.com/microsoft/vscode/issues/127967
