### ISSUE TITLE
Unable to view logs on private repositories

### ISSUE THREAD

**Issue by nostromoJohn** [github/vscode-github-actions#56]
**Describe the bug**
When attempting to view logs for a private repository, I get the following error message in VSCode after clicking the log button:
`Error running command github-actions.workflow.logs: cannot open gh-actions://<my_organization>/<repo_name>/%234552476769%20-%20<action_name>?12360270249. Detail: Could not load logs. This is likely caused by the extension that contributes github-actions.workflow.logs.`

I am logged into an account with organizational admin access both on VSCode and through the extension.

**To Reproduce**
1. Run a github action on a private repo inside an organization
2. Attempt to open logs
![image](https://user-images.githubusercontent.com/99584217/228493725-8af0765a-e13a-432f-8807-739cc189e0fb.png)
3. See error 
![image](https://user-images.githubusercontent.com/99584217/228493951-b740c95e-9900-46d1-b8ef-361d502b4327.png)

**Expected behavior**
Logs should show up as they normally would

**Extension Version**
`v0.25.3`

**Comment by mauriciosoares** [comment]
Possibly a duplicate of https://github.com/github/vscode-github-actions/issues/15

**Comment by nostromoJohn** [comment]
> Possibly a duplicate of #15

It may be caused by the same thing, but there's no telling since the original poster of #15 didn't include any reproduction steps in their description

**Comment by hdiass** [comment]
Having same error, reproduction steps is exactly what he (OP) shows in printscreens

**Comment by austinbutler** [comment]
For me it seems https://github.com/github/vscode-github-actions/pull/115 fixed it.

**Comment by nostromoJohn** [comment]
Works with 0.25.5 :) Closing this
