### ISSUE TITLE
Azure webapp deploy claims 'images' is a required input for 'with'

### ISSUE THREAD

**Issue by jasperfirecai2** [github/vscode-github-actions#58]
**Describe the bug**

When adding a step using `azure/webapps-deploy@v2` validation throws an error if the `with` block doesn't include an `images` input, even though it's an optional input

**To Reproduce**

1. Add a step to any job with `uses: azure/webapps-deploy@v2`
2. Add the `publish-profile` and `app-name` to the `with` inputs block
3. Validation will throw error that `images`is a required input

**Expected behavior**

`images` is an optional input

**Screenshots**

![image](https://user-images.githubusercontent.com/8398131/228517788-8e073468-84b2-4c89-a170-dc4481ef9c3f.png)

![image](https://user-images.githubusercontent.com/8398131/228516698-3868c7d0-5c08-4007-b29e-ce70bf1609d6.png)

**Extension Version**

`v0.25.3`

**Additional context**

[Workflow documentation](https://github.com/azure/webapps-deploy/tree/v2/)

**Comment by cschleiden** [comment]
The parameter is marked as `required` for the action. If this is optional, could you create an issue with the action's maintainer? 🙇 

https://github.com/Azure/webapps-deploy/blob/master/action.yml#L21
