### ISSUE TITLE
Actions extension allows unauthorized secret updates

### ISSUE THREAD

**Issue by MichaelKekic** [github/vscode-github-actions#62]
**Describe the bug**
A GitHub user has access to update secrets VIA the GitHub Actions extension in GitHub. The role of the user was originally "maintainer" and "write". However the user does NOT have admin access.  User does NOT have the ability to view the secrets via the setting tab for a repository. 

**To Reproduce**
1. Have a user with write access to a repo that does NOT have admin rights.
2. There must be an existing secret created by someone that does have Admin rights.
3. Use the VS code GitHub Actions to view `SETTINGS > Secrets> {secret name} > Update Secret`  Press enter
4. Secret value is then updated even though the user should NOT have the ability to do that. 

**Expected behavior**
I would expect a user with just "write" or "maintainer" access to NOT be able to update the values of existing secrets.

**Screenshots**
Not including screenshots.

**Extension Version**
`v0.25.3 `

**Additional context**
Tested with both Maintainer and Write roles.

**Comment by cschleiden** [comment]
The GitHub Actions secrets API requires `repo:write` scope in order to update secrets. There is a bit of a mismatch in the UI that the `Settings` tab also requires the admin role.

**Comment by edwinf** [comment]
@cschleiden Is that documented anywhere?  I cannot seem to find that distinction in any of the documentation.

https://docs.github.com/en/rest/actions/secrets?apiVersion=2022-11-28#create-or-update-a-repository-secret (says create and update require the same permission)

https://docs.github.com/en/enterprise-cloud@latest/organizations/managing-user-access-to-your-organizations-repositories/repository-roles-for-an-organization (Doesn't call out creating / updating secrets at all but that write is for people actively contributing and "write" can't change settings)

https://docs.github.com/en/enterprise-cloud@latest/actions/security-guides/encrypted-secrets#creating-encrypted-secrets-for-a-repository (calls out you need to be an admin to create secrets).

The ability to change a secret for an action to anyone with write permissions when creating them is locked to an admin role seems to be a bigger issue that most people wouldn't expect permissions wise.
