### ISSUE TITLE
Unable to find reusable workflow

### ISSUE THREAD

**Issue by Zageron** [github/vscode-github-actions#68]
**Describe the bug**
My reusable workflows aren't being found by the static analysis.

**To Reproduce**
1. Create a workflow.
2. Create a reusable workflow.
3. Try to include it in the base workflow.
4. Github Action will run successfully, vsc will complain with an error.

**Expected behavior**
Should not be an error if the reusable workflow functions on github.

**Screenshots**
![image](https://user-images.githubusercontent.com/1892473/228740365-a9d7c356-f716-4661-86fb-c1bde34b3e79.png)

**Extension Version**
`v0.25.3`

**Comment by KetchupOnMyKetchup** [comment]
Tested this on Windows and repro'd the issue. On Mac the issue doesn't happen. Appears to be an issue with pathing on Windows.

**Comment by KetchupOnMyKetchup** [comment]
The PR has been completed and the fix will be available in our upcoming release v0.25.6 planned for release April 21 2023.

**Comment by Zageron** [comment]
Thank you very much.

**Comment by KetchupOnMyKetchup** [comment]
The change is live and released on our new version `v0.25.6`! Thank you all so much for your support in helping report bugs and great repro steps!

**Comment by Maus3rSR** [comment]
Same here

v0.25.7

My setup :

Version: 1.79.0 (user setup)
Commit: b380da4ef1ee00e224a15c1d4d9793e27c2b6302
Date: 2023-06-07T14:26:35.552Z
Electron: 22.5.5
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.22621

**Comment by peter-byun** [comment]
try referencing the workflow like [the document](https://docs.github.com/en/actions/sharing-automations/reusing-workflows#creating-a-reusable-workflow) suggests.
```
uses: {your-org or user name}/{repository name}/.github/workflows/{workflow name}.yml@{branch}
```
