### ISSUE TITLE
Local test runs

### ISSUE THREAD

**Issue by MulverineX** [github/vscode-github-actions#70]
**Is your feature request related to a problem? Please describe.**
Currently, even with the features this extension provides, it is difficult to know whether an Action will work when deployed. This makes debugging slow, difficult, and costly (if you're using paid runner minutes). 

**Describe the solution you'd like**
It would be useful if this extension could setup, handle, & run the `act` utility locally; natively on linux & macos, utilizing WSL on windows.

**Comment by cschleiden** [comment]
Thanks for filing this. Unfortunately, this is not something that we are planning to do in the context of this extension. You might want to post in the official GitHub Actions community forums: https://github.com/orgs/community/discussions/categories/actions.

**Comment by ohhmm** [comment]
https://github.com/alphaxek/github-actions-locally
