### ISSUE TITLE
Number of checks displayed inside GH action is limited to 30

### ISSUE THREAD

**Issue by pere-pleo** [github/vscode-github-actions#72]
**Describe the bug**
Number of checks displayed inside GH action seems to be limited to 30. I see that the GH action failed and when I expand the menu to check the individual checks I cannot see the failing one. They are all in green because the one that failed is the 39th. 

The number 30 is my guess as I counted and it was a nice round number.

**To Reproduce**
- Get a GH action with more than 30 checks.
- Get one placed in the >30th position to fail.
- You will see a red icon on the GH action but when you expand the menu you should not see the failing one.

**Expected behavior**
- All checks inside a GH action are displayed

**Screenshots**
<img width="54" alt="Screenshot 2023-03-30 at 10 49 52" src="https://user-images.githubusercontent.com/90062357/228799027-b0e95a56-580d-4d13-bf1c-d407732fe4fd.png">

**Extension Version**
`v0.25.3`

**Additional context**

**Comment by muzimuzhi** [comment]
I guess the limit 30 came from the default `per_page` value, see
- https://docs.github.com/en/rest/guides/using-pagination-in-the-rest-api?apiVersion=2022-11-28 and
- for example https://docs.github.com/en/rest/actions/workflow-runs?apiVersion=2022-11-28

Currently in the source code there are multiple places using `per_page: 100`.  But as the original author of this extension commented in https://github.com/cschleiden/vscode-github-actions/issues/151#issuecomment-1106921339,

> Ideally the extension should paginate until there are no more workflows.

**Comment by KetchupOnMyKetchup** [comment]
I am going to bump the amount of displayed workflows to 100 for now.

The reason that it is set to 30 is because the default for `per_page` (see below) is 30.
![image](https://github.com/github/vscode-github-actions/assets/7976517/24310429-07b5-4040-b259-1b543c06bdf6)

It looks like in other parts of the code we set `per_page: 100` for things like variables and secrets and perhaps this API call was left out previously.

If there is a good use case in the future we can discuss getting more workflows, but I think for most use cases, displaying 100 workflows will be enough.

**Comment by KetchupOnMyKetchup** [comment]
Ok after discussion, the plan is:

1. Cut off workflow runs to most recent 100
2. Get all jobs per run and paginate using oktokit
3. Get all workflows and paginate using octokit

Links to similar requests:
- https://github.com/cschleiden/vscode-github-actions/issues/151#issuecomment-1106921339
- https://github.com/github/c2c-actions-experience/issues/7087

Link to PR doing pagination:
- https://github.com/github/actions-languageservices/pull/110

Use:
`this.gitHubRepoContext.client.paginate`

**Comment by KetchupOnMyKetchup** [comment]
This is now available in the newly released version `0.25.5`, thank you so much for submitting this feedback!
