### ISSUE TITLE
Publish to OpenVSX

### ISSUE THREAD

**Issue by janpio** [github/vscode-github-actions#73]
It would be great if this new extension would also be available at openvsx.org, as the old one was: https://open-vsx.org/extension/cschleiden/vscode-github-actions 

OpenVSX is an open alternative to the official VSCode Marketplace that is used by variants of VSCode. 

I for example would love to be able to use this extension in Gitpod, which uses openvsx to install extensions in their editor.

**Comment by janpio** [comment]
Happy to contribute the GitHub Actions workflow code in a PR if this would be accepted. We have been publishing the Prisma extension to OpenVSX for ages and it works nicely: https://github.com/prisma/language-tools/blob/53c215ce3050154ba7607739120bc96bc6c9bb9f/.github/workflows/7_publish.yml#L79-L107

**Comment by kalrish** [comment]
> We are having an internal discussion about this, […].

Some of your extensions are [already on Open VSX](https://open-vsx.org/namespace/GitHub), @felipesu19. One of them, _CodeQL_, is published by @aeisenberg, who works at GitHub too and so might contribute to this discussion. The other two extensions, _GitHub Pull Requests and Issues_ and _GitHub Theme_, seem to be mirrored by Open VSX itself. If Open VSX indeed can mirror extensions from the [Visual Studio Code Marketplace](https://marketplace.visualstudio.com/VSCode), that might be the most comfortable option for you.

**Comment by aeisenberg** [comment]
For the CodeQL extension, we have a [release](https://github.com/github/vscode-codeql/blob/main/.github/workflows/release.yml) action that will publish to both vscode marketplace and openvsx (gated by deployment environments). It's pretty straightforward. It just requires setting up the environments and adding the secrets.

**Comment by kalrish** [comment]
Thank you for chiming in so quickly, @aeisenberg :).

**Comment by jirutka** [comment]
@felipesu19, can you please release a new version so it will get published on OpenVSX? It’s still not available there.

**Comment by lrstanley** [comment]
Looks like the publish workflow isn't working, so even though a new release was cut, they aren't making their way to OpenVSX.

https://github.com/github/vscode-github-actions/actions/runs/6099539777/job/16552069376#step:3:11

```
Run npx ovsx publish -p $OPEN_VSX_TOKEN *.vsix
npm WARN exec The following package was not found and will be installed: ovsx@0.8.3
❌  Insufficient access rights for publisher: GitHub
See the documentation for more information:
https://github.com/eclipse/openvsx/wiki/Publishing-Extensions
Error: Process completed with exit code 1.
```

@felipesu19 is this something you'd be able to look at?

**Comment by sean-krail** [comment]
@felipesu19, can this be re-opened as the extension is not being published to OpenVSX due to the above permission issued @lrstanley found. Thanks!
