### ISSUE TITLE
Error when using the github.vscode-github-actions extension in Codespaces in vscode.dev

### ISSUE THREAD

**Issue by devopsjester** [github/vscode-github-actions#74]
**Describe the bug**
When using the `github.vscode-github-actions` extension in Codespaces in vscode.dev, any attempt to trigger a workflow run, re-run, or modify settings (e.g. adding a repository secret or variable) fails and an error toast pops up (bottom-right corner), saying "Could not create workflow dispatch. Resource not accessible by integration."

**To Reproduce**
1. Create a codespace in a repo that has at least one workflow.
2. Open in codespace (vscode opens in <codespace instance name>.github.dev
3. Install the `github.vscode-github-actions` extension
4. Open the `Github Actions` extension side-bar
5. Either select a workflow and click on the `trigger workflow` button, or right-click a workflow that already ran at least once and click the `rerun workflow run` context menu option.
6. See error.

**Expected behavior**
I expect the workflow to be triggered, just as it would when running in VsCode-desktop.

**Screenshots**
![image](https://user-images.githubusercontent.com/1774556/228864258-901e03c7-afe3-437d-b928-354d12c5c142.png)

**Extension Version**
`v0.25.3`

**Comment by maxisam** [comment]
my case is similar, but I don't have any error message.
But rerun works for me. I just can't trigger a new workflow run.

```
Version: 1.77.0 (user setup)
Commit: 7f329fe6c66b0f86ae1574c2911b681ad5a45d63
Date: 2023-03-29T10:02:16.981Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Windows_NT x64 10.0.22621
Sandboxed: No
```

**Comment by KetchupOnMyKetchup** [comment]
I have this work tracked in the remote repository future enhancements batch (https://github.com/github/vscode-github-actions/issues/103) to ensure we don't lose track of this issue, however we currently aren't supporting remote repositories at this time.  I am going to close this for now so we can keep track of open issues that we are currently working on.
