### ISSUE TITLE
Do not use the pop-up input box for variable/secrets creation

### ISSUE THREAD

**Issue by qc00** [github/vscode-github-actions#79]
**Is your feature request related to a problem? Please describe.**
The pop-up input box in VS Code dismisses itself as soon as it looses focus, making it hard to 
use copy and paste the values (when the clipboard is already occupied by the variable name).

**Describe the solution you'd like**
Use an editable table like those seen in many database UIs in the sidebar
OR
Use a dialog box that does not disappear when loosing focus

**Comment by joshmgross** [comment]
#35 should fix this

**Comment by KetchupOnMyKetchup** [comment]
Fixed with this PR: https://github.com/github/vscode-github-actions/pull/85
