### ISSUE TITLE
Integrate actionlint

### ISSUE THREAD

**Issue by rollingmoai** [github/vscode-github-actions#82]
**Is your feature request related to a problem? Please describe.**
It would be nice to integrate actionlint to make use some of its features in this extension.

**Describe the solution you'd like**
Integrate actionlint in this extension.

**Additional context**
https://github.com/rhysd/actionlint

```[tasklist]
```

**Comment by elbrenn** [comment]
Thanks for the request. We aren't planning to integrate any command line linting here, but if there are specific validation features you'd like to see in the vscode editor, we'd love to hear about them 🙂
