### ISSUE TITLE
Can't trigger a new workflow run

### ISSUE THREAD

**Issue by maxisam** [github/vscode-github-actions#83]
**Describe the bug**
Can't trigger a new workflow run. However, rerun works fine.

**To Reproduce**
- install extension 
- trigger a new workflow run

**Expected behavior**
It should trigger a new workflow run

**Extension Version**
`v0.25.3`

**Additional context**
```
Version: 1.77.0 (user setup)
Commit: 7f329fe6c66b0f86ae1574c2911b681ad5a45d63
Date: 2023-03-29T10:02:16.981Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Windows_NT x64 10.0.22621
Sandboxed: No
```

**Comment by KetchupOnMyKetchup** [comment]
@maxisam - Could you let me know if you see a button to trigger the run or if you see any errors that you could send us? Could we please see a screenshot as well? Thank you!
