### ISSUE TITLE
Syntax highlighting for expressions does not match showcase screenshots

### ISSUE THREAD

**Issue by AdamRaichu** [github/vscode-github-actions#84]
**Describe the bug**
When using the extension, expression syntax (`${{ context.value }}`) is not highlighted like in README examples.

**To Reproduce**
1. Open this repo with the extension installed.
2. Navigate to `.github/workflows/release.yml#L50`.
3. Observe that highlighting for expression syntax does not work and treats it as a string.

**Expected behavior**
The highlighting should match what the showcase screenshots in the README show.

![image](https://user-images.githubusercontent.com/91494019/229850142-ec395531-cc9e-44c4-ac12-da9b2ffe6cda.png)

**Screenshots**

![image](https://user-images.githubusercontent.com/91494019/229848558-ac22cdd2-43a0-41a3-87b6-9743e3eecd95.png)

**Extension Version**
`v0.23.0` (web)

**Additional context**
Note: I disabled prettier (my only other yaml extension) while testing to make sure this was not caused by another extension.

I know the title specifically says expressions, but this really applies to everything.

**Comment by joshmgross** [comment]
@AdamRaichu it's possible this is caused by your color theme not having different colors for the expression syntax highlighting. Does it work if you use a different color theme?

**Comment by cschleiden** [comment]
@AdamRaichu did you manually set the mode of the file to `YAML`? Could you try switching it to `GitHub Actions Workflow`? 

![CleanShot 2023-04-04 at 09 52 42@2x](https://user-images.githubusercontent.com/2201819/229863523-1d990d8e-b4a4-4196-93a9-4f82e5d1e7cb.png)

**Comment by AdamRaichu** [comment]
@cschleiden Thank you, that was the problem. I guess the language id was leftover from before I downloaded the extension.
