### ISSUE TITLE
Improve dev experience work for Windows and Codespaces + Document changes

### ISSUE THREAD

**Issue by KetchupOnMyKetchup** [github/vscode-github-actions#89]
On Windows in `package.json` we need to modify the single quotes to escaped double quotes in order to run commands:

```
npm run lint
npm test
npm run format
```

```
"scripts": {
    "build": "tsc --build tsconfig.build.json",
    "clean": "rimraf dist",
    "format": "prettier --write \"**/*.ts\"",
    "format-check": "prettier --check \"**/*.ts\"",
    "lint": "eslint \"src/**/*.ts\"",
    "lint-fix": "eslint --fix \"src/**/*.ts\"",
    "prepublishOnly": "npm run build && npm run test",
    "test": "cross-env NODE_OPTIONS=\"--experimental-vm-modules\" jest",
    "test-watch": "NODE_OPTIONS=\"--experimental-vm-modules\" jest --watch",
    "watch": "tsc --build tsconfig.build.json --watch"
  },
```

Specifically to run npm test:
1. Go to https://github.com/kentcdodds/cross-env and run `npm install --save-dev cross-env`
2. Change to `"test": "cross-env NODE_OPTIONS=\"--experimental-vm-modules\" jest",` (already modified above)

Issues with Codespaces: It is very slow to load new window with VS Code with local changes.

To do for Windows:
1. Most likely we can change the package.json in all the repos to have escaped double quotes, but need to test on Mac to make sure it still works like that.
2. Install cross-env as a dependency so its installed with `npm i` OR find an alternative.. because according to their GH repo its been archived (see https://github.com/kentcdodds/cross-env). So another similar library would be better.

**Comment by KetchupOnMyKetchup** [comment]
There is also as issue where on Windows it seems to be missing source control repos for language server so the UI for source control won't work.

Mac:

**Comment by andrewakim** [comment]
I was chatting with the Codespaces team and they also found that loading secrets/variables won't work with a repo-scoped token in the web client.

![image](https://github.com/github/vscode-github-actions/assets/6799182/3d7655d3-1477-4951-a99d-30991e330ca1)
